### ISSUE TITLE
Cant install framework using pod

### ISSUE THREAD

**Issue by BlackGold-1989** [berbix/berbix-ios-spec#1]
When installing pod, I met that issue.

[!] Error installing Berbix
[!] Failed to download 'Berbix': [!] /usr/bin/git clone https://github.com/berbix/berbix-ios-spec.git /var/folders/kk/wzvm4b0j67b8hwsllvyj6mcw0000gn/T/d20210517-22172-cnyn8d --template= --single-branch --depth 1 --branch 1.10.2

Cloning into '/var/folders/kk/wzvm4b0j67b8hwsllvyj6mcw0000gn/T/d20210517-22172-cnyn8d'...
warning: Could not find remote branch 1.10.2 to clone.
fatal: Remote branch 1.10.2 not found in upstream origin

**Comment by benbeltzer** [comment]
Hi @BlackGold-1989, a few things

- we would highly suggest using `2.0.0-rc04`. This is technically a pre-release, but we'll be releasing `2.0.0` very shortly, which will contain a major upgrade to our platform
- What does the berbix section of your Podfile look like? It's hard to provide any insight without seeing that. It should look like the following:
```
  source 'https://github.com/CocoaPods/Specs.git'
  source 'git@github.com:berbix/berbix-ios-spec.git'
  pod 'Berbix', '2.0.0-rc04'
```

**Comment by BlackGold-1989** [comment]
I already added that sentences but met a little other issue.
Added my screenshot when installing pod.
![Screen Shot 2021-05-19 at 4 17 05 AM](https://user-images.githubusercontent.com/58547693/118724924-75a0ba80-b859-11eb-8956-3e4c01e54a26.png)
